FROM nikolaik/python-nodejs:python3.9-nodejs14-slim
ENV TERRAFORM_VERSION=0.13.7
RUN apt-get update && apt-get install -y unzip curl jq apt-transport-https ca-certificates gnupg2 software-properties-common
RUN curl https://apt.secrethub.io | bash
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable"
RUN apt-get update && apt-get install -y docker-ce-cli

RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/bin

RUN curl https://cli-assets.heroku.com/install.sh | sh
RUN mkdir -p ~/.terraform.d/plugins && curl -SfL https://github.com/secrethub/terraform-provider-secrethub/releases/latest/download/terraform-provider-secrethub-linux-amd64.tar.gz | tar zxf - -C ~/.terraform.d/plugins

RUN pip3 install awscli
RUN apt-get install -y git make rsync

