version: 2.1
orbs:
    secrethub: secrethub/cli@1.1.0
jobs:
    build_and_test:
        working_directory: ~/app
        docker:
            -   image: vdtn359/news-ci
        steps:
            - secrethub/install
            - checkout
            -   restore_cache:
                    key: dependency-cache-{{ checksum "common/config/rush/pnpm-lock.yaml" }}
            -   run:
                    name: Rush check
                    command: |
                        node common/scripts/install-run-rush.js check
            -   run:
                    name: Install node_modules
                    command: |
                        node common/scripts/install-run-rush.js install
            -   save_cache:
                    key: dependency-cache-{{ checksum "common/config/rush/pnpm-lock.yaml" }}
                    paths:
                        - common/temp/pnpm-store
            -   restore_cache:
                    key: next-cache
            -   run:
                    name: Build
                    command: node common/scripts/install-run-rush.js build
            -   save_cache:
                    key: next-cache
                    paths:
                        - apps/web/.next/cache
            -   run:
                    name: Test
                    command: node common/scripts/install-run-rush.js test
            -   persist_to_workspace:
                    root: /root
                    paths:
                        - app
                        - .rush
    release:
        working_directory: ~/app
        docker:
            -   image: vdtn359/news-ci
        environment:
            AWS_REGION: ap-southeast-2
            AWS_ACCESS_KEY_ID: secrethub://vdtn359/start/vdtn359-news/aws-access-key-id
            AWS_SECRET_ACCESS_KEY: secrethub://vdtn359/start/vdtn359-news/aws-secret-access-key
            NPM_TOKEN: secrethub://vdtn359/start/vdtn359-news/npm-token
            GH_TOKEN: secrethub://vdtn359/start/vdtn359-news/github-token
            DOCKER_PASS: secrethub://vdtn359/start/vdtn359-news/docker-pass
            DOCKER_USER: secrethub://vdtn359/start/vdtn359-news/docker-user
            HEROKU_API_KEY: secrethub://vdtn359/start/vdtn359-news/heroku-token
        steps:
            - secrethub/install
            -   attach_workspace:
                    at: /root
            -   add_ssh_keys:
                    fingerprints:
                        - "12:17:e9:d6:19:9d:77:be:d1:bd:d9:0a:e2:f9:7e:b7"
            -   secrethub/exec:
                    step-name: Configure user
                    command: |
                        git config user.email vdtn359@gmail.com
                        git config user.name "Tuan Nguyen"
                        mkdir -p ~/.ssh
                        ssh-keygen -F github.com || ssh-keyscan github.com >> ~/.ssh/known_hosts
            -   secrethub/exec:
                    step-name: Release packages
                    command: |
                        node common/scripts/install-run-rush.js version --bump --target-branch release --ignore-git-hooks
                        node common/scripts/install-run-rush.js publish -p --include-all --version-policy packageVersion --target-branch release
            -   secrethub/exec:
                    step-name: Deploy crawler
                    command: make releaseCrawler
            -   secrethub/exec:
                    step-name: Deploy scheduler
                    command: make releaseScheduler
            - setup_remote_docker
            -   secrethub/exec:
                    step-name: Prepare credentails
                    command: |
                        echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
                        curl https://cli-assets.heroku.com/install.sh | sh
                        heroku container:login
            -   secrethub/exec:
                    step-name: Deploy web
                    command: make releaseWeb
            -   secrethub/exec:
                    step-name: Deploy worker
                    command: make releaseWorker
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_and_test
            -   release:
                    requires:
                        - build_and_test
                    filters:
                        branches:
                            only:
                                - release
